{% set name = "opentelemetry-exporter-datadog" %}
{% set version = "0.30b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-datadog-{{ version }}.tar.gz
  sha256: 841e315d3812518b8fe7301d5aadf2c9e864844aa62629c595df63c21c0cb6b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - ddtrace >=0.34.0,<0.47.0
    - opentelemetry-api >=1.3,<2.dev0
    - opentelemetry-sdk >=1.3,<2.dev0
    - opentelemetry-semantic-conventions ==0.30b0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/exporter/opentelemetry-exporter-datadog
  summary: Datadog Span Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE.Apache

extra:
  recipe-maintainers:
    - mariusvniekerk
