{% set name = "opentelemetry-exporter-datadog" %}
{% set version = "0.30b0" %}

# Common to all opentelemetry python libraries
{% set preoffset = 20 %}
{% set vsegments = version.split('.') %}
{% set vsegments = version.split('.') %}
{% set canonical_minor = (vsegments[1] | int) if (vsegments[0] == '1') else (vsegments[1].split('b')[0] | int) - preoffset %}
{% set vpre = '0.{}b0'.format(canonical_minor + preoffset ) %}
{% set vrel = '1.{}'.format(canonical_minor) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-datadog-{{ version }}.tar.gz
  sha256: 841e315d3812518b8fe7301d5aadf2c9e864844aa62629c595df63c21c0cb6b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ddtrace <0.47.0,>=0.34.0
    - opentelemetry-api ~=1.3
    - opentelemetry-sdk ~=1.3
    - opentelemetry-semantic-conventions ==0.30b0
    - python >=3.6

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.datadog
    - opentelemetry.exporter.datadog.propagator
  commands:
    - pip check || true
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/exporter/opentelemetry-exporter-datadog
  summary: Datadog Span Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE.Apache

extra:
  recipe-maintainers:
    - mariusvniekerk
